version: "3.9"
services:
  backend:
    build: ./backend
    container_name: server
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/server
    stdin_open: true
    tty: true
    environment:
      - WATCHPACK_POLLING=true


  
  frontend:
    build: ./frontend
    container_name: client
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    environment:
      - WATCHPACK_POLLING=true

